# Generated by Django 5.2.5 on 2025-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='established',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='programs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='no_of_seats',
            field=models.PositiveIntegerField(),
        ),
    ]
