# Generated by Django 5.2.5 on 2025-09-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_college_established_college_programs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='programs',
        ),
        migrations.AddField(
            model_name='college',
            name='type_of_institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
