# Generated by Django 5.2.5 on 2025-09-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_college_programs_college_type_of_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='type_of_institution',
        ),
    ]
