# Generated by Django 5.2.5 on 2025-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_college_type_of_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='type_of_institution',
            field=models.BooleanField(default=False),
        ),
    ]
