# Generated by Django 4.2.20 on 2025-09-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_college_type_of_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Code', max_length=50)),
                ('color', models.CharField(default='bg-gradient-primary', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.JSONField(default=list)),
                ('jobs', models.JSONField(default=list)),
                ('higher_studies', models.JSONField(default=list)),
                ('entrepreneurship', models.JSONField(default=list)),
                ('placements', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_path', to='api.branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.stream'),
        ),
    ]
