# Generated by Django 4.2.20 on 2025-09-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_branch_stream_careerpath_branch_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='entrepreneurship',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='higher_studies',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='jobs',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='subjects',
            field=models.CharField(max_length=150),
        ),
    ]
